### ISSUE TITLE
Implement Scss linting in Sky

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [blackbaud/skyux1#463]
We should implement scss linting as part of our build process. 

If we stick with compiling scss with ruby, we should look at these libraries:
- https://github.com/brigade/scss-lint 
- https://github.com/ahmednuaman/grunt-scss-lint

@Blackbaud-ChrisBellande has come up with the following overrides to the default configuration for scss-lint that we should start with:

```
linters:
  ImportPath:
    enabled: false
  Indentation:
    width: 4
  PropertySortOrder:
    enabled: false
  SelectorFormat:
    class_convention: 'bb\-membership\-[a-z0-9]+(\-[a-z0-9]+)*'
  FinalNewline:
    enabled: false
  StringQuotes:
    style: double_quotes
```
